log_file_path: C:/Users/Public/Daybreak Game Company/Installed Games/EverQuest/Logs/eqlog_Nebsk_teek.txt
output_directory: ''
polling_interval_ms: 1000
parallel_processing: true
email_smtp_server: smtp.gmail.com
email_smtp_port: 587
email_username: your-email@gmail.com
email_password: your-app-password
email_from: your-email@gmail.com
email_to: recipient@gmail.com
email_enable_ssl: true
# IMAP settings for receiving emails (uses SMTP credentials as defaults if not specified)
email_imap_server: imap.gmail.com
email_imap_port: 993
email_imap_enable_ssl: true
# Email monitoring poll interval in seconds (default: 30)
email_poll_interval_seconds: 30

# Process targeting configuration
# Set to true to target all EQGame.exe processes, false to target specific ones
target_all_processes: false
# List of specific process IDs to target (when target_all_processes is false)
target_process_ids: [1234, 5678]
# List of specific process names to target (when target_all_processes is false)
# Note: Since only EQGame processes are shown, process names are redundant
target_process_names: []
regex_rules:
- name: hello_world_response
  pattern: '.*hello # world.*'
  action_type: command
  action_value: 'g # Goodbye'
  enabled: true
- name: attack_minions
  pattern: .*Attack my minions.*
  enabled: true
  actions:
  - type: keystroke
    value: Ctrl + 1
    delay_ms: 2500
    enabled: true
  - type: command
    value: g at delaying
    enabled: true
- name: test
  pattern: .*clarice.*
  action_type: keystroke
  action_value: g woot
  enabled: true
- name: email_test
  pattern: .*email test.*
  action_type: email
  action_value: Test email from EQ Log Automator
  enabled: true
